development:
  adapter: postgresql
  encoding: utf8
  database: calacanisfanclub_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: calacanisfanclub_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: calacanisfanclub_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST


